#!/bin/sh
LIBS_NOT_FOUND="$(ldd $1 | grep 'not found' | sed 's/ .*//;s/\t//' | sort | uniq)"

for x in $LIBS_NOT_FOUND; do
  candidates=$(nix-locate -w --top-level $x)

  if [ $(echo "$candidates" | wc -l) -gt 1 ]; then
    echo "$candidates" | fzf --ansi | sed 's/ .*//'
  else
    echo "$candidates" | sed 's/ .*//'
  fi
done
