#!/bin/sh
PACKAGES="$*"
SCRIPT=${SCRIPT:-bash}

FHS=$(cat << EOF | bash
nix-build --no-out-link -E 'with import <nixpkgs> {};
  buildFHSUserEnv {
    name = "fhs";
    targetPkgs = p: with p; [ $PACKAGES ];
    runScript = "$SCRIPT";
  }
'
EOF
)
"$FHS/bin/fhs"
