#!/bin/sh

set -x
export SCRIPT
SCRIPT=$(realpath "$1")
export BASESCRIPT=$(basename "$SCRIPT")

SCRIPTDIR=$(dirname "$0")

if ! [ -e ~/.cache/nix-autobahn/"$BASESCRIPT".nix ]; then
  LIBS=$("$SCRIPTDIR/nix-autobahn-find-libs" "$SCRIPT")
  "$SCRIPTDIR/nix-autobahn-ld-shell" "$LIBS"
fi
nix-shell ~/.cache/nix-autobahn/"$BASESCRIPT".nix
